# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - badminton

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://ghcr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_e092e3ad7ca94f0cbe346ef27b423a66 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_e433dc6f02314b07a5aed5b915f16e14 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ghcr.io/${{ secrets.AzureAppService_ContainerUsername_e092e3ad7ca94f0cbe346ef27b423a66 }}/mcr.microsoft.com/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'badminton'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_66fdf4dcf8334493b6fc549c088a95ae }}
        images: 'ghcr.io/${{ secrets.AzureAppService_ContainerUsername_e092e3ad7ca94f0cbe346ef27b423a66 }}/mcr.microsoft.com/appsvc/staticsite:${{ github.sha }}'